// lib/codeThemes.ts
import type { CSSProperties } from "react"

export const darkTheme: Record<string, CSSProperties> = {
  "code[class*='language-']": { color: "#cdd6f4", background: "none", fontFamily: 'Menlo, Monaco, "Courier New", monospace' },
  "pre[class*='language-']": { color: "#cdd6f4", background: "none", fontFamily: 'Menlo, Monaco, "Courier New", monospace' },
  comment: { color: "#6c7086", fontStyle: "italic" },
  prolog: { color: "#6c7086" },
  doctype: { color: "#6c7086" },
  cdata: { color: "#6c7086" },
  punctuation: { color: "#9399b2" },
  namespace: { opacity: 0.7 },
  property: { color: "#89dceb" },
  tag: { color: "#f38ba8" },
  boolean: { color: "#fab387" },
  number: { color: "#fab387" },
  constant: { color: "#fab387" },
  symbol: { color: "#fab387" },
  deleted: { color: "#f38ba8" },
  selector: { color: "#cba6f7" },
  "attr-name": { color: "#89dceb" },
  string: { color: "#a6e3a1" },
  char: { color: "#a6e3a1" },
  builtin: { color: "#a6e3a1" },
  inserted: { color: "#a6e3a1" },
  operator: { color: "#cdd6f4" },
  entity: { color: "#cdd6f4" },
  url: { color: "#89b4fa" },
  variable: { color: "#cdd6f4" },
  atrule: { color: "#cba6f7" },
  "attr-value": { color: "#a6e3a1" },
  keyword: { color: "#cba6f7" },
  function: { color: "#89b4fa" },
  "class-name": { color: "#a6e3a1" },
  regex: { color: "#f9e2af" },
  important: { color: "#fab387", fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
}

export const lightTheme: Record<string, CSSProperties> = {
  "code[class*='language-']": { color: "#24292e", background: "none", fontFamily: 'Menlo, Monaco, "Courier New", monospace' },
  "pre[class*='language-']": { color: "#24292e", background: "none", fontFamily: 'Menlo, Monaco, "Courier New", monospace' },
  comment: { color: "#9ea7b3", fontStyle: "italic" },
  prolog: { color: "#9ea7b3" },
  doctype: { color: "#9ea7b3" },
  cdata: { color: "#9ea7b3" },
  punctuation: { color: "#6e7781" },
  namespace: { opacity: 0.7 },
  property: { color: "#0550ae" },
  tag: { color: "#cf222e" },
  boolean: { color: "#cf222e" },
  number: { color: "#0550ae" },
  constant: { color: "#0550ae" },
  symbol: { color: "#0550ae" },
  deleted: { color: "#cf222e" },
  selector: { color: "#8250df" },
  "attr-name": { color: "#0550ae" },
  string: { color: "#0a3069" },
  char: { color: "#0a3069" },
  builtin: { color: "#8250df" },
  inserted: { color: "#116329" },
  operator: { color: "#24292e" },
  entity: { color: "#24292e" },
  url: { color: "#0550ae" },
  variable: { color: "#24292e" },
  atrule: { color: "#8250df" },
  "attr-value": { color: "#0a3069" },
  keyword: { color: "#cf222e" },
  function: { color: "#8250df" },
  "class-name": { color: "#953800" },
  regex: { color: "#116329" },
  important: { color: "#cf222e", fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
}
